# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Reed W. R. Bratches
title_with_suffix: Reed W. R. Bratches, PhD
subtitle_1: Assistant Professor, School of Nursing
subtitle_2: University of Alabama at Birmingham (UAB)
# subtitle_3:
email: ReedB@uab.edu
# phone: 
address: 1701 University Blvd, Birmingham, AL 35294
map: 33.50270996672542, -86.80273572932231
description: >- # this means to ignore newlines until "baseurl:"
  Reed Bratches is an Assistant Professor in the School of Nursing at the University of Alabama at Birmingham (UAB)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.reedbratches.com/" # the base hostname & protocol for your site, e.g. http://example.com
author: rbratches
twitter:
  username: rbratches
  card: summary
twitter_username: rbratches
github_username:  reedbratches
googlescholar_username: GCc4ebIAAAAJ&hl
researchgate_username: Reed-W-R-Bratches-2198529957
orcid_username: 0000-0001-9446-7098
cv_pdf: /assets/pdfs/BRATCHES_CV.pdf
profile_img: /assets/img/reed.png
biography_title: Biography
interests: [Family Caregivers, Persons Living with Dementia, Medication Refusals, Medication Management, Medication Adherence, Care-Resistant Behavior]
education: 
- title: "Postdoctoral Fellow, COERE"
  detail: "University of Alabama at Birmingham"
- title: PhD in Health Services Research, 2022
  detail: Dartmouth College
- title: MPH, 2019
  detail: Dartmouth College
- title: MALS in Cultural Studies, 2018
  detail: Dartmouth College
- title: BA in Government, 2013
  detail: Franklin and Marshall College

publications: true
page_excerpts: true
show_excerpts: true

custom_footer: <p><i class="fa-solid fa-car-side"></i> Looking for my substack? Check out <a  class="text-decoration-none" href="https://thedriversbriefing.substack.com/">the Driver's Briefing.</a></p>


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
